# _config.yml

# Site settings
title: Tyson Limato: Portfolio
description: A brief description of your portfolio
url: "https://tlimato.github.io" # the base hostname & protocol for your site

# Build settings
theme: al-folio # You can choose a different theme based on your preference
plugins:
  - jekyll-feed

# GitHub Pages settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

